name: Format the code

on:
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jitterbit/get-changed-files@v1
        id: files
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Cloud Formation Formatter
        run: |
          gh release download --repo aws-cloudformation/rain --pattern "*_linux-amd64.zip" --output "rain.zip"
          unzip -j "rain.zip" "*/rain"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Formatting
        run: |
          for changed_file in ${{ steps.files.outputs.all }}; do 
            if [[ ${changed_file} == *.json ]] ; then 
              echo "Linting json file ${changed_file}"
              #cat ${changed_file} | jq . > /dev/null
              ./rain fmt -j -w ${changed_file}
            fi
          done

      - name: Commit and push changes
        run: |
          git config --global user.name "jeff-grubb"
          git config --global user.email "jeff.grubb@fox.com"
        
          git commit -a -m "Format files"
          git push
