name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: jitterbit/get-changed-files@v1
        id: files
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Cloud Formation Formatter
        run: |
          gh release download --repo aws-cloudformation/rain --pattern "*_linux-amd64.zip" --output "rain.zip"
          unzip -j "rain.zip" "*/rain"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check format
        run: |
          for changed_file in ${{ steps.files.outputs.added_modified }}; do 
            echo "Checking ${changed_file}." 
            if [[ ${changed_file} == *.json ]] ; then 
              echo "Linting json file ${changed_file}"
              ./rain fmt --verify ${changed_file}
            fi
          done