name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: jitterbit/get-changed-files@v1
        id: abc
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Printing
        run: |
          for changed_file in ${{ steps.files.outputs.added_modified }}; do echo "Checking %{changed_file}." ; if [[ changed_file == *.json ]] ; then echo "Do something with this JSON file ${changed_file}." ; fi ; done